version: '3.4'
services:
  divi.avado.dnp.dappnode.eth:
    image: 'divi.avado.dnp.dappnode.eth:0.0.1'
    build:
      context: ./build
      args:
        - VERSION=2.5.1
    environment:
      - EXTRA_OPTS=-testnet
    volumes:
      - 'data:/package/data/divi'
    ports:
      - '51472:51472' # mainnet
      - '51474:51474' # testnet
      - '51473:51473' # mainnet rpc
      - '51475:51475' # testnet rpc
      - '80:80'
      - '443:443'
    logging:
      options:
        max-size: 10m
        max-file: '3'
volumes:
  data: {}
